export const LOG_IN = 'APP/LOG_IN'
export const LOG_OUT = 'APP/LOG_OUT'
export const SHOW_LOADER = 'APP/SHOW_LOADER'
export const HIDE_LOADER = 'APP/HIDE_LOADER'

export const SET_FLIGHTS_DATE = 'FLIGHTS/SET_FLIGHTS_DATE'
export const REQUEST_FLIGHTS = 'FLIGHTS/REQUEST_FLIGHTS'
export const GET_FLIGHTS = 'FLIGHTS/GET_FLIGHTS'
export const TOGGLE_FAVOURITE = 'FLIGHTS/TOGGLE_FAVOURITE'